### ISSUE TITLE
signal missing question

### ISSUE THREAD

**Issue by jonathanxixu** [lizhenghn123/zl_threadpool#1]
I have read your code CPP03.
When program wants to stop,  you will broadcast condition signal, but what if some thread is busy executing some job, I am afraid your condition signal will miss, and when this thread finish its job, it will still hold in blocking wait and can not exit as you wish.

**Comment by lizhenghn123** [comment]
No, it's not happen.
When main thread call stop, it will be set `isRunning_ = false`, see https://github.com/lizhenghn123/zl_threadpool/blob/master/ThreadPoolCpp03/ThreadPool.cpp#L48.
So when work thread finish it;s job, the while-loop is not continue, see https://github.com/lizhenghn123/zl_threadpool/blob/master/ThreadPoolCpp03/ThreadPool.cpp#L97.

**Comment by jonathanxixu** [comment]
Hum, you are right, double check about count, condition, etc. is very necessary.
